# Generated by Django 3.2.19 on 2023-05-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='body',
            new_name='message',
        ),
    ]
