# Generated by Django 3.2.19 on 2023-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_remove_jobapplication_supporting_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(max_length=80),
        ),
    ]
