# Generated by Django 3.2.19 on 2023-05-16 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('github_username', models.CharField(blank=True, max_length=200)),
                ('job_seeker', models.BooleanField(default=False)),
                ('recruiter', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.IntegerField()),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('interests', models.TextField()),
                ('roles_open_to', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=True)),
                ('reported', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
