# Generated by Django 3.2.19 on 2023-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='years_experience',
            field=models.IntegerField(null=True),
        ),
    ]
