# Generated by Django 3.2.19 on 2023-05-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.userprofile')),
            ],
        ),
    ]
